name: Sample build CI
on:
  push:
    branches:
      - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout
            uses: actions/checkout@v3
        -   name: Configure Tags
            run: |
                TAG=$(git describe --tags --abbrev=7 --always)
                echo "TAG=$TAG" >> $GITHUB_ENV
        -   name: Verify Tags
            run: |
                echo "Using tag $TAG"
                